#!/bin/bash

if [ $1 == "install" ]
then

docker-compose down -v
docker-compose up -d

docker exec postgres ./scripts/pgsql_install.sh
docker exec broker ./scripts/broker_install.sh
docker exec kore ./scripts/kore_install.sh docker-compose up -d

elif [ $1 == "stop" ] 
then
docker-compose stop

elif [ $1 == "start" ]
then

docker-compose start

docker exec postgres ./scripts/pgsql_start.sh
docker exec broker ./scripts/broker_start.sh
docker exec kore ./scripts/kore_start.sh

elif [ $1 == "exec" ]
then

docker exec -it $2 /bin/ash

elif [ $1 == "reset" ]
then

docker exec postgres psql -U postgres -c "delete from acl; delete from follow; delete from users where id not like 'admin'"
docker exec broker rabbitmqctl stop_app
docker exec broker rabbitmqctl reset
docker exec broker rabbitmqctl start_app

fi
