version: "3"

networks:
  kore-net:
    driver: bridge

services:

  kore:
    image: ideam/kore
    container_name: kore
    hostname: kore
    restart: always
    hostname: kore
    ports:
      - "8888:8888"
    networks:
      - kore-net
    cap_add:
      - ALL

  broker:
    image: ideam/kore-broker
    container_name: broker 
    restart: always
    hostname: broker
    ports:
      - "5672:5672"
      - "1883:1883"
      - "15672:15672"
    networks:
      - kore-net
    cap_add:
      - ALL
  
  postgres:
    image: ideam/postgres
    container_name: postgres
    hostname: postgres
    restart: always
    networks:
      - kore-net
    cap_add:
      - ALL
