#!/bin/bash

set -e 

docker-compose down 
docker-compose up -d 

docker cp setup/postgres.sh postgres:/
docker exec postgres chmod +x postgres.sh
docker exec postgres ./postgres.sh
docker cp postgres:/postgres_pwd .

pwd=`cat postgres_pwd | cut -d ":" -f 2`

sed 's/postgres_pwd/'$pwd'/g' authenticator/src/authenticator.c > authenticator/src/authenticator_new.c
sed 's/postgres_pwd/'$pwd'/g' kore-publisher/src/kore-publisher.c > kore-publisher/src/kore-publisher_new.c

docker cp authenticator/ broker:/
docker cp setup/broker.sh broker:/
docker exec broker chmod +x broker.sh
docker exec broker ./broker.sh 

docker cp kore-publisher/ kore:/
docker cp setup/kore.sh kore:/
docker exec kore chmod +x kore.sh
docker exec kore ./kore.sh 
