#!/bin/bash

set -e 

docker-compose down -v 
docker-compose up -d 

docker exec postgres ./scripts/pgsql_install.sh
docker exec broker ./scripts/broker_install.sh 
docker exec kore ./scripts/kore_install.sh 
