#!/bin/bash

sudo chown -R 0:0 ../kore-publisher/jail
sudo chmod 1111 ../kore-publisher/jail
sudo chmod 000 ../kore-publisher/jail/etc

sudo chown -R 0:0 ../authenticator/jail
sudo chmod 1111 ../authenticator/jail
sudo chmod 000 ../authenticator/jail/etc

docker-compose down -v
docker-compose up -d

docker exec postgres ./scripts/pgsql_install.sh
docker exec broker ./scripts/broker_install.sh
docker exec kore ./scripts/kore_install.sh
