#!/bin/bash

directory=`dirname $0`
cd $directory

sudo chown -R 0:0 ../kore-publisher/jail
sudo chmod 1555 ../kore-publisher/jail
sudo chmod 1555 ../kore-publisher/jail/etc

sudo chown -R 0:0 ../authenticator/jail
sudo chmod 1555 ../authenticator/jail
sudo chmod 1555 ../authenticator/jail/etc

docker-compose down -v
docker-compose up -d

docker exec postgres ./scripts/pgsql_install.sh
docker exec broker ./scripts/broker_install.sh
docker exec kore ./scripts/kore_install.sh
docker exec postgres python /scripts/daemon.py > daemon.log &
