group HTTPS GET /owner/follow-requests
owner2 -> middleware:**id**: string\r**apikey**: string
end

group 200 OK
middleware -> owner2: [\l\t{\t\r\t\t"**follow-id**": string,\r\t\t"**from**": string,\r\t\t"**to**": string,\r\t\t"**time**": string,\r\t\t"**permission**": string,\r\t\t"**topic**": string,\r\t\t"**validity**": string\r\t},\l\t ...\l]
end

group HTTPS POST /owner/share
owner2 -> middleware : **id**: string\r**apikey**: string\r**follow-id**: string
end

group 200 OK
middleware -> owner2
end
