@startuml
hide footbox



...
group HTTPS POST /entity/follow
subscriber -> middleware: **id**: string\r**apikey**: string\r**to**: string\r**topic**: string\r**permission**: string\r**validity**: string
end

group 202 ACCEPTED
middleware -> subscriber: {"**follow-id-read**": string, "**follow-id-write**": string}
end

...

    actor "owner of publisher"

	participant publisher



middleware -> "owner of publisher" : notification

...

group HTTPS POST /owner/share                                                    
"owner of publisher" -> middleware : **id**: string\r**apikey**: string\r**follow-id**: string 
end                                                                              
                                                                                 
group 200 OK                                                                     
middleware -> "owner of publisher"                                                             
end                                                                              

...

group HTTPS POST /entity/publish
publisher -> middleware: **id**: string\r**apikey**: string\r**to**: string\r**subject**: string\r**message-type**: string\r**content-type**: string\r\r**<message in body>**
end

group 202 ACCEPTED
middleware -> publisher:
end

...
group HTTPS GET /entity/subscribe

subscriber -> middleware: **id**: string\r**apikey**: string\r**to**: string\r**num-messages**: string\r**message-type**: string
end

group 200 OK
middleware -> subscriber: [\l\t{\t\r\t\t"**sent-by**": string,\r\t\t"**from**": string,\r\t\t"**subject**": string,\r\t\t"**content-type**": string,\r\t\t"**body**": string,\r\t},\l\t ...\l]
end

@enduml
