actor admin
hide footbox

hnote over admin : on localhost
...

group HTTPS POST /admin/register-owner
admin -> middleware: **id**: string\r**apikey**: string\r**owner**: string
end

create owner
middleware -> owner : new

group 201 CREATED
middleware -> admin: {"id": string, "apikey": string}
end

...

group HTTPS POST /admin/register-owner

owner -> middleware: **id**: string\r**apikey**: string\r**entity**: string

end

create entity
middleware -> entity : new

group 201 CREATED
middleware -> owner: {"id": string, "apikey": string}
end

@enduml
