actor admin
hide footbox

hnote over admin : logged on middleware 
...

group HTTPS POST /admin/register-owner
admin -> middleware: **id**: string\r**apikey**: string\r**owner**: string
end

create owner
middleware -> owner : new account

group 201 CREATED
middleware -> admin: {"**id**": string, "**apikey**": string}
end

@enduml
