actor admin
hide footbox

admin -> middleware: **HTTPS GET /register-owner**\r**id**: string\r**apikey**: string\r**owner**: string

create owner
middleware -> owner : new

group 201 CREATED
middleware -> admin: {"id": string, "apikey": string}
end

...


owner -> middleware: **HTTPS GET /register**\r**id**: string\r**apikey**: string\r**entity**: string

create entity
middleware -> entity : new

group 201 CREATED
middleware -> owner: {"id": string, "apikey": string}
end

@enduml
